spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AchanZhang/config-repo-demo
#          search-paths: config-repo-demo
#          username:
#          password:

server:
  port: 3318

# 配置服务注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/